def b(num):
    # type: (int) -> int
    return 1 << num


# general
DEACTIVE_FLAG_NO_RECIPE = b(0)
DEACTIVE_FLAG_OUTPUT_FULL = b(1)
DEACTIVE_FLAG_NO_INPUT = b(2)
DEACTIVE_FLAG_STRUCTURE_BROKEN = b(3)
DEACTIVE_FLAG_STRUCTURE_BLOCK_LACK = b(4)

# appliance
DEACTIVE_FLAG_POWER_LACK = b(5)
DEACTIVE_FLAG_FLUID_NOT_MATCH = b(6)
DEACTIVE_FLAG_FLUID_FULL = b(7)

# generator
DEACTIVE_FLAG_POWER_FULL = b(5)
