# coding=utf-8


class Machinery:
    AlloyFurnace = "machinery_alloy_furnace"
    Assembler = "machinery_assembler"
    Charger = "machinery_charger"
    Compressor = "machinery_compressor"
    CreativeGenerator = "machinery_creative_generator"
    CreativePowerAcceptor = "machinery_creative_power_acceptor"
    Digger = "machinery_digger"
    DistillatorChamber = "machinery_distillator_chamber"
    ElectricCrafter = "machinery_electric_crafter"
    ElectricHeater = "machinery_electric_heater"
    FarmingStation = "machinery_farming_station"
    # Fermenter = "machinery_fermenter"
    FluidCondenser = "machinery_fluid_condenser"
    FluidSplitter = "machinery_fluid_splitter"
    Forester = "machinery_forester"
    Freezer = "machinery_freezer"
    GeoThermalGenerator = "machinery_geothermal_generator"
    HoverTextDisplayer = "machinery_hover_text_displayer"
    # HeavyCompressor = "machinery_heavy_compressor"
    HoverTextDisplayer = "machinery_hover_text_displayer"
    HydroponicBase = "machinery_hydroponic_base"
    HydroponicBed = "machinery_hydroponic_bed"
    ItemSplitter = "machinery_item_splitter"
    Macerator = "machinery_macerator"
    MachineryWorkstation = "machinery_machinery_workstation"
    MagmaCentrifuge = "machinery_magma_centrifuge"
    MagmaFurnace = "machinery_magma_furnace"
    MetalPress = "machinery_metal_press"
    # MiniMiner = "machinery_mini_miner"
    Mixer = "machinery_mixer"
    OilExtractor = "machinery_oil_extractor"
    Pump = "machinery_pump"
    RedstoneFurnace = "machinery_redstone_furnace"
    SolarPanel = "machinery_solar_panel"
    ThermalGenerator = "machinery_thermal_generator"
    WindGenerator = "machinery_wind_generator"


class Plots:
    Plot1 = "general_plot_1"
    Plot2 = "general_plot_2"
